config/routes.rb
Rails.application.routes.draw do
  root 'routes#index'
  resources :routes, only: [:index, :show]
end

app/models/route.rb
class Route < ActiveRecord::Base
  validates :agency_id, presence: true
  validates :obid, presence: true

  def display_name
    long_name.blank? ? "Route #{ self.short_name }" : long_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  def index
    @routes = Route.all
  end

  def show
    route = Route.find(params[:id])
    @route = Route::AddBusMap.call(route)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_map_javascript_tags.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<script type="text/javascript">

  handler = Gmaps.build('Google');
  handler.buildMap(
    {
      provider: {
        disableDefaultUI: true
        // here you can pass other Google Maps API options here
      },
      internal: {
        id: 'map'
      }
    },
    function() {
      markers = handler.addMarkers(<%=raw @route.bus_map.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    }
  );

</script>

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    = csrf_meta_tag

  %body
    %div.top
    %div.row
      = yield

app/views/routes/_map.html.erb
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

app/views/routes/_routes_navigation.html.erb
<a class= "button" data-dropdown="drop1" aria-controls="drop1" aria-expanded="false">Bus Routes</a>
<ul id="drop1" class="f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
  <% @routes.each do |route| %>
    <li><%= link_to route.display_name, route_path(route) %></li>
  <% end %>
</ul>

app/views/routes/index.html.haml
%h3 Select a Route from the Dropdown Menu Below

= render partial: "routes_navigation"

app/views/routes/show.html.haml
%h3 Most Recent Bus Locations for #{ @route.display_name}

= render partial: "map"
= render partial: "layouts/map_javascript_tags"